"""update admin_premium

Revision ID: adf2e19c60ed
Revises: ab53cb8504e6
Create Date: 2024-04-13 21:02:41.734866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'adf2e19c60ed'
down_revision = 'ab53cb8504e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin__premium', schema=None) as batch_op:
        batch_op.add_column(sa.Column('action', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin__premium', schema=None) as batch_op:
        batch_op.drop_column('timestamp')
        batch_op.drop_column('action')

    # ### end Alembic commands ###
