"""update card model

Revision ID: d1e1561c62cc
Revises: adf2e19c60ed
Create Date: 2024-04-14 20:13:02.164310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1e1561c62cc'
down_revision = 'adf2e19c60ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card', schema=None) as batch_op:
        batch_op.add_column(sa.Column('month_hash', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('year_hash', sa.String(length=255), nullable=False))
        batch_op.drop_column('expiration_date_hash')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expiration_date_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.drop_column('year_hash')
        batch_op.drop_column('month_hash')

    # ### end Alembic commands ###
