@startuml
state choice <<choice>>
state fork_state <<fork>>
state join_state <<join>>

skinparam maxMessageSize 10

[*] --left> Активность_не_начата : Пользователь еще не начал активность
[*] --> choice : Пользователь хочет начать активность
choice --> fork_state : Пользователь  выбирает вид активности
fork_state --> Забег_начат : Пользователь выбрал бег
fork_state --> Велотренировка_начата : Пользователь выбрал велосипед
fork_state --> Заплыв_начат : Пользователь выбрал плавание
Забег_начат --> join_state
Велотренировка_начата --> join_state
Заплыв_начат --> join_state
join_state --> Активность_приостановлена : Пользователь поставил на паузу
join_state --> Активность_сохранена : Пользователь сохранил активность
Активность_приостановлена --> fork_state : Пользователь убрал с паузы
Активность_сохранена --> [*] : Пользователь закончил активность

@enduml