@startuml
actor "Неавторизованный пользователь" as unautorizedUser
participant "Клиент" as client
participant "Сервер" as server
database "База данных" as db

unautorizedUser -> client: Восстановить пароль
activate client

client -> client: Проверка валидности
break "Некорректные данные"
    client --> unautorizedUser: Показать ошибку
end

client -> server: Отправка введенных данных
activate server
server -> db: Отправка введенных данных
activate db
db --> server: Пароль изменен
deactivate db
server --> client: Успешное восстановление пароля
deactivate server
client --> unautorizedUser: Пароль изменен
deactivate client
@enduml